# Generated by Django 3.2.8 on 2021-11-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211103_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default=None, help_text='Book', max_length=200),
            preserve_default=False,
        ),
    ]
